name: Build quantlib-swig-devenv Docker images
on: workflow_dispatch
jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v2
    - name: Checkout latest QuantLib master
      uses: actions/checkout@v2
      with:
        repository: lballabio/QuantLib
        path: quantlib-swig-devenv/QuantLib
    - name: Build Docker images
      run: |
        rm -rf quantlib-swig-devenv/QuantLib/.git
        make quantlib-swig-devenv TAG=rolling
    - name: Login to DockerHub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_HUB_USER }}
        password: ${{ secrets.DOCKER_HUB_TOKEN }}
    - name: Push Docker images
      run: |
        docker push lballabio/quantlib-swig-devenv
